# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\option.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_option(object):
    def setupUi(self, option):
        option.setObjectName("option")
        option.resize(750, 645)
        self.label = QtWidgets.QLabel(option)
        self.label.setGeometry(QtCore.QRect(240, 50, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 127);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(option)
        self.pushButton.setGeometry(QtCore.QRect(140, 290, 150, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(option)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 290, 150, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(option)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 290, 150, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(option)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 370, 150, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(option)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 370, 150, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(option)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 370, 150, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(option)
        self.label_2.setGeometry(QtCore.QRect(350, 600, 72, 15))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(option)
        QtCore.QMetaObject.connectSlotsByName(option)

    def retranslateUi(self, option):
        _translate = QtCore.QCoreApplication.translate
        option.setWindowTitle(_translate("option", "option"))
        self.label.setText(_translate("option", "油色谱诊断程序"))
        self.pushButton.setText(_translate("option", "分类模块"))
        self.pushButton_2.setText(_translate("option", "预测模块"))
        self.pushButton_3.setText(_translate("option", "通讯设置"))
        self.pushButton_4.setText(_translate("option", "告警记录"))
        self.pushButton_5.setText(_translate("option", "使用帮助"))
        self.pushButton_6.setText(_translate("option", "模型介绍"))
        self.label_2.setText(_translate("option", "欢迎使用"))
