# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QVBoxLayout, QMainWindow,QComboBox, QPushButton,QWidget,QFileDialog, QTableWidget, QTableWidgetItem,QMessageBox,QDialog
import pyqtgraph as pg
import numpy as np

class Ui_ycmk(object):
    def setupUi(self, ycmk):
        ycmk.setObjectName("ycmk")
        ycmk.resize(795, 675)
        self.label = QtWidgets.QLabel(ycmk)
        self.label.setGeometry(QtCore.QRect(310, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 127);")
        self.label.setObjectName("label")

        



        self.retranslateUi(ycmk)
        QtCore.QMetaObject.connectSlotsByName(ycmk)

    def retranslateUi(self, ycmk):
        _translate = QtCore.QCoreApplication.translate
        ycmk.setWindowTitle(_translate("ycmk", "predict"))
        self.label.setText(_translate("ycmk", "预测模块"))
