# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_METHODCONFIGURE(object):
    def setupUi(self, METHODCONFIGURE):
        METHODCONFIGURE.setObjectName("METHODCONFIGURE")
        METHODCONFIGURE.resize(766, 582)
        self.pushButton = QtWidgets.QPushButton(METHODCONFIGURE)
        self.pushButton.setGeometry(QtCore.QRect(170, 70, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(METHODCONFIGURE)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 61, 28))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(METHODCONFIGURE)
        self.listWidget.setGeometry(QtCore.QRect(91, 101, 256, 341))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(METHODCONFIGURE)
        self.label_2.setGeometry(QtCore.QRect(380, 80, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(METHODCONFIGURE)
        self.lineEdit.setGeometry(QtCore.QRect(380, 100, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(METHODCONFIGURE)
        self.label_3.setGeometry(QtCore.QRect(380, 140, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(METHODCONFIGURE)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 160, 201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(METHODCONFIGURE)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 160, 91, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(METHODCONFIGURE)
        self.label_4.setGeometry(QtCore.QRect(380, 200, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(METHODCONFIGURE)
        self.textEdit.setGeometry(QtCore.QRect(380, 230, 301, 211))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(METHODCONFIGURE)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 480, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(METHODCONFIGURE)
        self.label.setGeometry(QtCore.QRect(91, 63, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(METHODCONFIGURE)
        QtCore.QMetaObject.connectSlotsByName(METHODCONFIGURE)

    def retranslateUi(self, METHODCONFIGURE):
        _translate = QtCore.QCoreApplication.translate
        METHODCONFIGURE.setWindowTitle(_translate("METHODCONFIGURE", "METHODCONFIGURE"))
        self.pushButton.setText(_translate("METHODCONFIGURE", "添加"))
        self.pushButton_2.setText(_translate("METHODCONFIGURE", "删除"))
        self.label_2.setText(_translate("METHODCONFIGURE", "方法名称"))
        self.label_3.setText(_translate("METHODCONFIGURE", "实现文件"))
        self.pushButton_3.setText(_translate("METHODCONFIGURE", "浏览文件"))
        self.label_4.setText(_translate("METHODCONFIGURE", "参考文献"))
        self.pushButton_4.setText(_translate("METHODCONFIGURE", "保存"))
        self.label.setText(_translate("METHODCONFIGURE", "方法"))
