# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sybz(object):
    def setupUi(self, sybz):
        sybz.setObjectName("sybz")
        sybz.resize(795, 675)
        self.label_3 = QtWidgets.QLabel(sybz)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 0, 0);\n"
"color: rgb(85, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(sybz)
        self.groupBox.setGeometry(QtCore.QRect(120, 470, 601, 161))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(31, 51, 553, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.calendarWidget = QtWidgets.QCalendarWidget(sybz)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 140, 701, 311))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(sybz)
        QtCore.QMetaObject.connectSlotsByName(sybz)

    def retranslateUi(self, sybz):
        _translate = QtCore.QCoreApplication.translate
        sybz.setWindowTitle(_translate("sybz", "使用帮助"))
        self.label_3.setText(_translate("sybz", "使用帮助"))
        self.groupBox.setTitle(_translate("sybz", "提示"))
        self.label.setText(_translate("sybz", "1.本软件作用是对变压器油中气体含量进行分析。"))
        self.label_2.setText(_translate("sybz", "2.升级软件请联系wu9705@126.com"))
        self.label_4.setText(_translate("sybz", "3.账户密码为前三位"))
