# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mxjs(object):
    def setupUi(self, mxjs):
        mxjs.setObjectName("mxjs")
        mxjs.resize(795, 675)
        self.label_2 = QtWidgets.QLabel(mxjs)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 0, 0);\n"
"color: rgb(85, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(mxjs)
        self.pushButton.setGeometry(QtCore.QRect(190, 250, 200, 70))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mxjs)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 250, 200, 70))
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(mxjs)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 360, 200, 70))
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(mxjs)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 360, 200, 70))
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(mxjs)
        QtCore.QMetaObject.connectSlotsByName(mxjs)

    def retranslateUi(self, mxjs):
        _translate = QtCore.QCoreApplication.translate
        mxjs.setWindowTitle(_translate("mxjs", "模型介绍"))
        self.label_2.setText(_translate("mxjs", "模型介绍"))
        self.pushButton.setText(_translate("mxjs", "随机森林（RF）"))
        self.pushButton_2.setText(_translate("mxjs", "长短时记忆网络（LSTM）"))
        self.pushButton_4.setText(_translate("mxjs", "门控循环单元（GRU）"))
        self.pushButton_3.setText(_translate("mxjs", "卷积神经网络（CNN）"))
