# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bjjl(object):
    def setupUi(self, bjjl):
        bjjl.setObjectName("bjjl")
        bjjl.resize(795, 675)
        self.label = QtWidgets.QLabel(bjjl)
        self.label.setGeometry(QtCore.QRect(310, 30, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 127);")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(bjjl)
        self.tableWidget.setGeometry(QtCore.QRect(100, 210, 581, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(bjjl)
        self.pushButton.setGeometry(QtCore.QRect(370, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(bjjl)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(bjjl)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 500, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(bjjl)
        self.label_2.setGeometry(QtCore.QRect(330, 630, 141, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(bjjl)
        QtCore.QMetaObject.connectSlotsByName(bjjl)

    def retranslateUi(self, bjjl):
        _translate = QtCore.QCoreApplication.translate
        bjjl.setWindowTitle(_translate("bjjl", "报警记录"))
        self.label.setText(_translate("bjjl", "报警记录"))
        self.pushButton.setText(_translate("bjjl", "清空记录"))
        self.pushButton_2.setText(_translate("bjjl", "保存记录"))
        self.pushButton_3.setText(_translate("bjjl", "添加告警"))
        self.label_2.setText(_translate("bjjl", "TextLabel"))
