# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\登录.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_denglu(object):
    def setupUi(self, denglu):
        denglu.setObjectName("denglu")
        denglu.resize(730, 510)
        self.label = QtWidgets.QLabel(denglu)
        self.label.setGeometry(QtCore.QRect(170, 50, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(denglu)
        self.label_2.setGeometry(QtCore.QRect(260, 280, 72, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(denglu)
        self.label_3.setGeometry(QtCore.QRect(260, 340, 72, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(denglu)
        self.comboBox.setGeometry(QtCore.QRect(330, 290, 121, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(denglu)
        self.lineEdit.setGeometry(QtCore.QRect(330, 340, 121, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(denglu)
        self.pushButton.setGeometry(QtCore.QRect(280, 400, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(denglu)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 400, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(denglu)
        self.label_4.setGeometry(QtCore.QRect(0, -20, 731, 591))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\wuhongchou\\Desktop\\vs-pyqt\\56987273.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(denglu)
        QtCore.QMetaObject.connectSlotsByName(denglu)

    def retranslateUi(self, denglu):
        _translate = QtCore.QCoreApplication.translate
        denglu.setWindowTitle(_translate("denglu", "登录窗口"))
        self.label.setText(_translate("denglu", "变压器油色谱诊断程序V1.0"))
        self.label_2.setText(_translate("denglu", "账户"))
        self.label_3.setText(_translate("denglu", "密码"))
        self.pushButton.setText(_translate("denglu", "创建"))
        self.pushButton_2.setText(_translate("denglu", "登录"))
