# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wuhongchou\Desktop\vs-pyqt\密码错误.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mimacuowu(object):
    def setupUi(self, mimacuowu):
        mimacuowu.setObjectName("mimacuowu")
        mimacuowu.resize(400, 300)
        self.label = QtWidgets.QLabel(mimacuowu)
        self.label.setGeometry(QtCore.QRect(110, 100, 201, 61))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(mimacuowu)
        self.pushButton.setGeometry(QtCore.QRect(140, 170, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(mimacuowu)
        QtCore.QMetaObject.connectSlotsByName(mimacuowu)

    def retranslateUi(self, mimacuowu):
        _translate = QtCore.QCoreApplication.translate
        mimacuowu.setWindowTitle(_translate("mimacuowu", "密码错误"))
        self.label.setText(_translate("mimacuowu", "密码错误，请重新输入。。。"))
        self.pushButton.setText(_translate("mimacuowu", "确认"))
